# Note: the cluster this repo has been iterated on locally had Argo CD and
# Argo Rollouts installed from their raw upstream install.yaml manifests
# (see gitops/application.yaml's bootstrap comment). Terraform installs the
# equivalent via each project's official Helm chart instead — same
# controllers/CRDs, but declarative and idempotent through Terraform rather
# than a one-off `kubectl apply -f <url>`.

resource "kubernetes_namespace" "argocd" {
  metadata {
    name = "argocd"
  }
  depends_on = [null_resource.k3d_cluster]
}

resource "helm_release" "argocd" {
  name       = "argocd"
  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-cd"
  version    = var.argocd_chart_version != "" ? var.argocd_chart_version : null
  namespace  = kubernetes_namespace.argocd.metadata[0].name

  wait    = true
  timeout = 600
}

resource "kubernetes_namespace" "argo_rollouts" {
  metadata {
    name = "argo-rollouts"
  }
  depends_on = [null_resource.k3d_cluster]
}

resource "helm_release" "argo_rollouts" {
  name       = "argo-rollouts"
  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-rollouts"
  version    = var.argo_rollouts_chart_version != "" ? var.argo_rollouts_chart_version : null
  namespace  = kubernetes_namespace.argo_rollouts.metadata[0].name

  wait    = true
  timeout = 600
}

# Argo CD's initial admin password, generated by the chart on first
# install. Read back only for the convenience output below — Terraform
# never manages its value.
data "kubernetes_secret" "argocd_admin_password" {
  metadata {
    name      = "argocd-initial-admin-secret"
    namespace = kubernetes_namespace.argocd.metadata[0].name
  }
  depends_on = [helm_release.argocd]
}
