apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "posts-api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "posts-api.labels" . | nindent 4 }}
data:
  TYPEORM_CONNECTION: mysql
  TYPEORM_HOST: {{ include "posts-api.dbHost" . }}
  TYPEORM_PORT: {{ .Values.database.port | quote }}
  TYPEORM_SYNCHRONIZE: {{ .Values.app.synchronize | quote }}
  TYPEORM_ENTITIES: dist/entity/*.js
  TYPEORM_MIGRATIONS: dist/migration/*.js
  TYPEORM_SUBSCRIBERS: dist/subscriber/*.js
  PORT: {{ .Values.app.port | quote }}
