{{- if not .Values.argoRollouts.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "posts-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "posts-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "posts-api.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    {{- include "posts-api.podTemplate" . | nindent 4 }}
{{- end }}
