apiVersion: v1
kind: Service
metadata:
  name: {{ include "posts-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "posts-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "posts-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
